### ISSUE TITLE
Generate randomized exercises

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#100]
Using [StevenClontz/mastr](https://github.com/StevenClontz/Mastr/) and a little bit of scripting for each standard, we should generate thousands of example exercises for use in practice and assessment. (See also #99 when writing these.)

**Comment by siwelwerd** [comment]
Along with this, we should be able to automate the generation of a table of matrices and their RREF that includes every matrix needed in every assessment problem, along with distractors.

**Comment by StevenClontz** [comment]
Yeah: there's two steps to this. (1) Mastr currently generates a PreTeXt XML document with a question and answer; it probably should be an extension of PreTeXt (or its own syntax) so we can add this kind of metadata (`<hints><hint>RREF=...</hint><hint distractor="true">unrelatedRREF=...</hint></hints>`). (2) Right now Mastr only creates online homework at https://mastr.clontz.org/ and my separate SbgRails app generates quizzes from these exercises - the quiz generation needs to be moved into Mastr somehow.

**Comment by siwelwerd** [comment]
I actually don't think Mastr should generate assessments necessarily. I think it should generate libraries of problems (i.e. a list of N problems for each standard). I would find it useful to have two of these libraries: one for HW problems, and the other a problem bank for assessments.

The assessment problem bank could then be fed into either your SbgRails app, or the perl script I use, or whatever the instructor wants.

**Comment by StevenClontz** [comment]
Yeah, for each library (hw/assessment), we need two things. (1) A LaTeX document that can be copy/pasted by laypersons as needed. (2) An XML or JSON file for easy parsing by scripts for advanced users. But ultimately I want Mastr to include a client-side app to automate things for laypeople as well.

**Comment by siwelwerd** [comment]
What exactly do you mean by "client-side app"? Something like the perl script I use could be distributed with Mastr, which would allow clients to generate assessments by modifying a LaTeX document class to their liking and running the script. If you mean something user-facing in your SBGRails ecosystem, that is probably an order of magnitude more effort.

(If it is not clear, there are two subtexts on my mind here: how much of this could we implement by January to make our lives easier teaching this next semester, and the rest for the TBIL grant project)

**Comment by StevenClontz** [comment]
In this context a client-side app is a Javascript web application that can be hosted on a static web server (e.g. GitHub pages). We don't want our users to have to open a terminal for a Perl script to use the TBIL Resource Library to its fullest - ultimately I don't want them to have to mess with LaTeX at all. I want them to go to a webpage, check the boxes of the standards they want to assess, then click "Download Quiz PDF".

**Comment by siwelwerd** [comment]
I started adding some of the Mastr input files for some of the standards. I think it makes more sense to keep them with the course, than with the Mastr project.

**Comment by StevenClontz** [comment]
This sounds fine to me. After last week, I'm less focused on developing [another standard](https://xkcd.com/927/) for generating math exercises. Instead I learned what I need to create static copies of [OPL](http://webwork.maa.org/wiki/Open_Problem_Library#.XffEinVKg5k) exercises without running a WebWork server, which we may be able to take advantage of for some standards (I don't know what LA stuff exists). In any case, I found momentum from other folks with the latter project; less so for developing Mastr.

**Comment by siwelwerd** [comment]
I tried poking around the OPL website, and am not having much luck readily identifying a collection of LA problems. It seems to be organized by university (?).

Webwork is nice because it is Perl, not python, but it's also ugly (and unclear if we can use the power of Sage?). Now that I have done a handful of LA standards for Mastr it is actually pretty quick and will serve my needs for the spring.

**Comment by StevenClontz** [comment]
Everything except V is serviceable. Please reopen any of the other modules' issues if you want me to tweak anything (unless you want to fix it yourself).

**Comment by StevenClontz** [comment]
Note that I am cheating and using `<p>(a) foo</p><p>(b) bar</p>` in place of itemized lists; I hope this is good enough until I find a more scalable solution for transforming the PreTeXt.

**Comment by siwelwerd** [comment]
Some problems (like E1 and E2) generate extra whitespace in the tex output. It looks like this is because there is a conditional at the beginning of these. I am not sure if the "right" way to fix it lies in the templates or the Mastr code. I could probably do something hacky with LaTeX to make it work for me if needed as well.

**Comment by StevenClontz** [comment]
You're referring to this?

```
\begin{exercise}
  \begin{exerciseTitle}E1 - Augmented Matrices (ver. 0)\end{exerciseTitle}
  \begin{exerciseStatement}
    
      Give an augmented matrix that represents the following system of linear equations.


      
\begin{align*}
  -2 \, x_{1} - 3 \, x_{2} + 6 \, x_{3} + 7 \, x_{4} &= 1 \\ 
  x_{1} + x_{2} - x_{3} - x_{4} &= 1 \\ 
  -2 \, x_{1} - 5 \, x_{3} - 7 \, x_{4} &= -7 \\ 
 \end{align*}

    
  \end{exerciseStatement}

  \begin{exerciseAnswer}
    
    
\[\left[\begin{array}{rrrr|r}
-2 & -3 & 6 & 7 & 1 \\
1 & 1 & -1 & -1 & 1 \\
-2 & 0 & -5 & -7 & -7
\end{array}\right]\]

    
  \end{exerciseAnswer}
\end{exercise}
```

So yes, the extra newlines between the `\begin` and `\end` tags is likely from the lines that have ERB conditionals.

I think the immediate way to solve this (until I can refactor the templates altogether) is to do a replacement of all whitespace with a single space when outputting LaTeX. That way we only get newlines when we're supposed to (via tags like `<p>`). I'll see if that is an easy fix.

**Comment by StevenClontz** [comment]
Does this do what you want it to?

```
\begin{exercise}

  \begin{exerciseTitle}
E1 - Augmented Matrices (ver. 0)
\end{exerciseTitle}

  \begin{exerciseStatement}
 Give an augmented matrix that represents the following system of linear equations. \begin{align*} -2 \, x_{1} - 3 \, x_{2} + 6 \, x_{3} + 7 \, x_{4} &= 1 \\ x_{1} + x_{2} - x_{3} - x_{4} &= 1 \\ -2 \, x_{1} - 5 \, x_{3} - 7 \, x_{4} &= -7 \\ \end{align*} 
\end{exerciseStatement}


  \begin{exerciseAnswer}
 \[\left[\begin{array}{rrrr|r} -2 & -3 & 6 & 7 & 1 \\ 1 & 1 & -1 & -1 & 1 \\ -2 & 0 & -5 & -7 & -7 \end{array}\right]\] 
\end{exerciseAnswer}


\end{exercise}
```

**Comment by siwelwerd** [comment]
I think that will work.

**Comment by StevenClontz** [comment]
So the dcd7dcb commit in the mastr repo produces that kind of output. Try it and see if the LaTeX works better for you now.

**Comment by siwelwerd** [comment]
Looks good to me. I think that wraps this up.
