### ISSUE TITLE
Module E Mastr problems

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#104]
See #100

**Comment by StevenClontz** [comment]
Closed by e47eb5f34223c187baab3072730edc750deed652

By the way @siwelwerd be sure to git pull this and mastr when you get back from travel, and update any scripts accordingly. I've put in some work to clean house and document things (look at READMEs in this repo's exercise folder and the mastr repo).

**Comment by siwelwerd** [comment]
Is there a reason we switched E1 from going both ways? The problems right now only convert to an augmented matrix, none ask students to write a system from an augumented matrix (we previously had problems going both ways).

@StevenClontz : I am reopening, but feel free to justify and re-close if this was intentional.

**Comment by StevenClontz** [comment]
Nah you're right. I'll address this.
