### ISSUE TITLE
Module V Mastr Problems

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#105]
See #100

**Comment by siwelwerd** [comment]
I have a dozen or so types for V1 as of  b1d25cb . These will need thorough proofreading before this issue can be closed.

**Comment by StevenClontz** [comment]
@siwelwerd Are you okay with me changing any non-vector spaces that only fail the additive inverse property to have the student first prove that the additive identity exists?

**Comment by siwelwerd** [comment]
Sure. I went back and forth on how to deal with that, since that property only makes sense to check  when an additive identity exists.

**Comment by siwelwerd** [comment]
OK, rough versions of V1 and V4 are in the repository. I haven't had time to update my build script since you tinkered with the organization of things, so I haven't been able to compile things to see how they look. Currently in triage mode since catching up from travel has been interrupted by emergent house plumbing issues.

**Comment by StevenClontz** [comment]
I'm having lunch now and have a 1pm phone call. After that I'll finish reviewing V01 and look at V04

**Comment by StevenClontz** [comment]
I proofed V01 and I think it's good now. (You were overly pessimistic about the existence of additive identities.) I don't promise that all failing properties are included in our answers, but agree that the ones in our answers do fail; if a student presents one that fails not on our list, it's easy enough to check (and then we can add it to the generator).

Go to http://mastr.clontz.org/lin-alg/V01/ if you want to double-check. I left the `version N` info in it for now so you can find the 10 different versions `0-9`. I'll remove that Monday.

**Comment by StevenClontz** [comment]
V04 is up at http://mastr.clontz.org/lin-alg/V04/

I may refactor to use Sagemath vectors/variables and their latex output (so we won't have weirdness like `x^{2}3y`).

Can you look over everything on Monday and make sure we're happy with at least E and V?

**Comment by StevenClontz** [comment]
I realized that you probably were just missing a plus in that example I mentioned, but I went ahead and refactored anyway. Should be visible at that link momentarily.

**Comment by siwelwerd** [comment]
Thanks, there were probably some issues with things like 1x as well.

Drew Lewis
(251) 460-3120

Department of Mathematics and Statistics
University of South Alabama
411 University Boulevard North
Mobile, AL 36688-0002

**Comment by siwelwerd** [comment]
Proofreading notes:
- Small punctuation issue on V1
- I think V5 and V6 should probably ask about a set of vectors

I'll make these cosmetic changes when I am back in the office.
