### ISSUE TITLE
Module A Mastr problems

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#106]
See #100

**Comment by siwelwerd** [comment]
For A3 problems, be sure the kernel is nontrivial.

**Comment by StevenClontz** [comment]
I've done A2 and A3. I seem to recall you had an idea for A4, so I'll let you implement.

I think we should discuss your V1 and then decide how to approach A1.

**Comment by StevenClontz** [comment]
Closed by 844c547d37103646c2a62ac39aabec36d4407bad
