### ISSUE TITLE
Module M Mastr problems

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#107]
See #100

**Comment by StevenClontz** [comment]
Closed by 74c52be8fe194901a5f7adce816a1445e3995727

**Comment by StevenClontz** [comment]
50 seeds for each working exercise are up here https://mastr.clontz.org/

**Comment by siwelwerd** [comment]
Typo in prompt of M2 (invertible is mispelled two different ways :)

I think students would appreciate a name for the matrix in M3, so that they can write e.g. A^{-1}=... .
