### ISSUE TITLE
Module G Mastr problems

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#108]
See #100

**Comment by StevenClontz** [comment]
Closed by 6d55fbd075b9647afdce76d21c44b12d9dc1ad83

**Comment by siwelwerd** [comment]
G1 answers should probably mention the matrix multiplication part (e.g. PQA).
On G4, should "value" at the end of the prompt be "eigenvalue"?

**Comment by StevenClontz** [comment]
G1 also needs to have random ordering of P,Q. I'm working on these now.
