### ISSUE TITLE
Remove Module S from introduction

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#109]
The introduction still references a separate Module S.

**Comment by siwelwerd** [comment]
I tried to fix this by deleting two lines from tex/modules/0-I/index.tex . But when I do this, git thinks I haven't changed anything. Not sure if it is inadvertently being ignored? I didn't see anything obvious in .gitignore that would cause this.

**Comment by StevenClontz** [comment]
Well, I don't have trouble changing and committing the change (see a3523b7f), but apparently something about my build environment is screwed up: 

```
! Undefined control sequence.
l.1 \beamer@endinputifotherversion
```

So I cannot make a new `course-slides.pdf`.

**Comment by siwelwerd** [comment]
Something is messed up... when I try pulling, it thinks I have changes, but not when I push or stash?

drewlewis@ASILB0439-01 ~/math/teaching/tbil-la (master)
$ git pull
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 6 (delta 4), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (6/6), done.
From github.com:StevenClontz/tbil-la
   b4467fd..a3523b7  master     -> origin/master
Updating b4467fd..a3523b7
error: Your local changes to the following files would be overwritten by merge:
	tex/modules/0-I/index.tex
Please, commit your changes or stash them before you can merge.
Aborting
drewlewis@ASILB0439-01 ~/math/teaching/tbil-la (master)↓
$ git stash
No local changes to save
drewlewis@ASILB0439-01 ~/math/teaching/tbil-la (master)↓
$ git pull
Updating b4467fd..a3523b7
error: Your local changes to the following files would be overwritten by merge:
	tex/modules/0-I/index.tex
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by StevenClontz** [comment]
Yikes. What do `git status` and `git diff` say?

**Comment by siwelwerd** [comment]
drewlewis@ASILB0439-01 ~/math/teaching/tbil-la (master)↓
$ git status
On branch master
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working directory clean
drewlewis@ASILB0439-01 ~/math/teaching/tbil-la (master)↓
$ git diff
drewlewis@ASILB0439-01 ~/math/teaching/tbil-la (master)↓
$

**Comment by siwelwerd** [comment]
I had the file set as assume-unchanged for the local sectioning.

**Comment by StevenClontz** [comment]
TIL a new-to-me Git feature.

Can you rebuild with the updated module I?

**Comment by siwelwerd** [comment]
Just pushed the revised one in a3523b7 . Closing this issue, make a new issue if your build issues persist.
