### ISSUE TITLE
Module V tweaks

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#110]
We discussed a few tweaks to presenting vector spaces, adding a few more class activities.

Additionally, I am tempted to remove the complex numbers from the RAT. This is used only in Remark V.7, not in an activity. I am thinking replacing it with more set builder notation would be good (to help them with V4).

**Comment by siwelwerd** [comment]
Looks like we use complex numbers in V.25 as well, but that could be changed.

**Comment by StevenClontz** [comment]
I'm okay with dropping complex numbers.

**Comment by siwelwerd** [comment]
Okay, I'll make those adjustments. I am working through module V at the moment to make sure I have everything on the right day, so I will go ahead and make those tweaks. I'll let you know when the new activities and RATs are ready for proofreading.

**Comment by siwelwerd** [comment]
@StevenClontz Take a look at the two new RAT questions, Activity V.12, and Activity V.24. If you are happy or only have minor corrections, this issue can be closed.

**Comment by StevenClontz** [comment]
Looks good.
