### ISSUE TITLE
V02 typesetting/modifications

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#114]
Right now V02 tends to print off the edge of the page due to the long list of vectors.

I also like randomly asking about "span" rather than just asking about "linear combinations". But I also like the "and" being put in the question about linear combos (I predict at least one student will augment the matrix where "and" is, revealing a lack of mastery that needs to be addressed).

**Comment by siwelwerd** [comment]
My LaTeX code typesets them just fine -- not sure if I have just chosen optimal margins or what, as LaTeX is generally pretty dumb about overfull hboxes. I guess an easy fix would be to change <m> to <me> in 
https://github.com/StevenClontz/tbil-la/blob/86f7bb3b3e7175290e4bfe16d41ed5c0b1952cde/exercises/mastr/V02.xml.erb#L5

**Comment by StevenClontz** [comment]
Yeah I switched `\(math\)` to `\[math\]` by hand, but a change from `<m/>` to `<me/>` in the source would make it less susceptible to overfull hboxes.
