### ISSUE TITLE
Module V tweaks

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#115]
It would be instructive for this activity (V.31) if the result of RREF(the natural matrix) had a row of all zeros except for a 1 at the end.

**Comment by siwelwerd** [comment]
Looks like our slides are off by 1 -- I added an additional V1 activity in 5d4882166622eec049abe3b3a347e142048ba4f0 at the beginning of the semester, so your V.31 is the current repository's V.32.

I think V.23 and V.25 would be better if Part 1 said "Write an equation of polynomials/matrices".

**Comment by siwelwerd** [comment]
Fact V.31 probably should be revised to (also) say something about a vector equation.
V.32 - V.34 would go smoother with an emphasis on the systems, perhaps even a scaffolded part 1 to that effect.

I think this will apply elsewhere as well -- if we are requiring an explanation beyond "Row of zeroes" on assessments, we should explain better in the slides.

**Comment by StevenClontz** [comment]
This semester I am accepting "row of zeroes" since it's a characterization we establish in the slides. But I think I like a broader policy for this course that it is not sufficient for mastery to just point out a feature of a resulting matrix: you also have to interpret what that feature means (e.g. "The row of zeroes witnesses a possible contradiction of 0=1." might be okay?)

**Comment by siwelwerd** [comment]
I decided to go ahead and ask them to really explain when we say "Explain" on the assessments; on V3 in particular, I told them I want them making some reference to a system (either always being consistent, or potentially being inconsistent, upon augmenting). I am seeing fewer mistakes on the in-class activities when they go ahead and phrase things as a question about a system instead of jumping straight to writing down a matrix.

**Comment by StevenClontz** [comment]
I may do the same then, with more leniency for revisions in the next couple
weeks.

**Comment by StevenClontz** [comment]
We should confirm the sample solutions meet that standard

**Comment by siwelwerd** [comment]
I believe we changed all the sample solutions to meet this standard before the semester.

**Comment by StevenClontz** [comment]
Yeah I think so. It may also be worth rephrasing the exercises to explicitly ask them to rephrase the exercise as a question about linear systems. But rephrasing the exercises would be better to wait and do after the semester ends.

**Comment by siwelwerd** [comment]
I think Fact V.49 should be removed. Fact V.47 is good. Activity V.48 should be redone so that the last vector is independent of the first four (to emphasize that looking at [v_1 v_2 v_3 v_4 | v_5] is not sufficient).

**Comment by siwelwerd** [comment]
Activity V.71 could use names for the four subspaces.

**Comment by StevenClontz** [comment]
It's worth considering changing the canonical reason for linear (in)dependence in our activities. Right now we establish that a non-pivot column witnesses a linear system with infinitely-many solutions. In particular, this seems an (unnecessary?) step removed from the definition of linear dependence, which is that there exists a linear combination of vectors equal to another vector.

Would it be clearer if we instead had students use a non-pivot column to produce a linear combination to directly witness linear dependence, and when all columns are pivots otherwise note that any vector equation attempting to equate a linear combination of vectors to another vector would imply the contradiction 0=1, witnessing linear independence?

**Comment by StevenClontz** [comment]
Alternatively, maybe the "right" way to look at this is not that there are infinitely-many solutions, but that there's a non-trivial solution. Put that way, the non-trivial solution directly witnesses a linear combination breaking independence, and the lack of one directly witnesses that no such combination exists.

**Comment by siwelwerd** [comment]
Actually, "the" definition of linear dependence is that there is a nontrivial/infinitely many ways to construct the zero vector. This distinction is really only useful in the case of the set containing only the zero vector (which is linearly dependent).

`Alternatively, maybe the "right" way to look at this is not that there are infinitely-many solutions, but that there's a non-trivial solution.`

Those are saying the same thing. Do you want to emphasize this more?


I am certainly okay if students observe one vector is a linear combination of others, therefore the set is linearly dependent. But the assertion "Every column is a pivot column, therefore any vector equation attempting to equate a linear combination of vectors to another vector would imply the contradiction 0=1" requires some justification -- why is the RREF unchanged when the columns are permuted in every possible way?

**Comment by StevenClontz** [comment]
Your canonical definition of linear dependence is not what we define in our slides. We currently define dependence as "one vector in the set belongs to the span of the others" on slide V.44. Which still forces `\{\vec 0\}` to be dependent since `\operatorname{span}(\emptyset)=\{\vec 0\}`. But switching to yours might be more symmetric: spanning means `(linear combo)=v` has at least one solution, independence means `(linear combo)=0` has a unique solution, and basis means `(linear combo)=v` has a unique solution (which better reflects injection, surjection, and bijection of linear maps later).

After further thought I dislike my assertion you noted, for the reasons you note.

If we kept the existing definition of linear dependence in our slides, then there's value in emphasizing non-trivial solution (which is a result of having infinitely-many of course), since it's only (any one of) the non-trivial solutions that can be used to witness that one vector is in the span of the others. But I think I'm being convinced that we should change our basic definitions to those I use in the first paragraph, and have extension theorems that prove e.g. "in a linear dependent set, one vector must belong to the span of the others", "a basis is linearly independent and spanning".

I think a slide that contrasts the basic definitions and the "quick checks" of rows/columns that can be used if you don't need a full explanation might be useful to clear up some of the issues I'm seeing on my assessments.

**Comment by siwelwerd** [comment]
Yeah, I like "one vector is in the span of the others" as the intuitive/informal definition, and probably where we should start. *Then* develop the formal (canonical?) definition as a result of that, which better motivates our technique(s) for checking.

> I think a slide that contrasts the basic definitions and the "quick checks" of rows/columns that can be used if you don't need a full explanation might be useful to clear up some of the issues I'm seeing on my assessments

I almost want a "Quick check" environment for this sort of thing. But yes.

**Comment by StevenClontz** [comment]
I'm not exactly sure what you mean by "Quick check" environment, but I have been thinking along these lines: I think I like having "computational" standards which might require 2 demos of mastery and can be done with just quickly checking matrix features, and "writing" standards which only require 1 demo of mastery, but need full explanations. So the writing standards would be V1, V4, A1 obviously, but we could include something like "Explain how to find a basis for span{...}, using the formal definitions of spanning and independence."

**Comment by siwelwerd** [comment]
Right now we have a "Fact" environment, that says e.g. "Fact V.49 A set ... is linearly dependent iff every column is a pivot column". I would rather it say "Quick Check V.49 ..." to emphasize that is not complete reasoning.

**Comment by StevenClontz** [comment]
Oh duh. That's a good idea.

Thinking ahead, we can obviously hack PreTeXt to do whatever, but these are the canonical `theoremlike`s: https://pretextbook.org/doc/guide/html/overview-math-results.html I'd need to dig deeper to see what the "correct" way of customizing one would be. (Or we could just always include "Quick Check" in the title of such facts.)

**Comment by siwelwerd** [comment]
We can rename one of them if we feel so inclined. https://pretextbook.org/doc/guide/html/basics-ch-rename.html

This seems hacky though. I feel like there ought to be a way to define our own tag, inheriting from another tag if need be.

**Comment by StevenClontz** [comment]
Yeah we could write some minimal `XSL` that imports the core `mathbook-html.xsl` to let us customize things. I think the least brittle solution would be to define a custom attribute, e.g. `<fact variant="quick-check">...</fact>` so that the source would still be valid PreTeXt if used in another context (it would just be missing the custom title). I'd ping the PreTeXt dev google group to see if they could convince me otherwise before going down that path.

**Comment by StevenClontz** [comment]
I think for V3/V5, our students may need to write out augmented matrices. E.g. for V3

![image](https://user-images.githubusercontent.com/1559632/78999977-60634380-7b11-11ea-9d5a-77fb05f72d66.png)

It seems most of my students are memorizing the sentence about the vector equation, but possibly not seeing the relationship to the matrix work.

**Comment by StevenClontz** [comment]
This may also be addressed by including vector equations in the E1 standard too.

**Comment by siwelwerd** [comment]
I see that as well, they get an R and a comment like "What system of equations are you referring to?". I don't know that the problems need to change though.

**Comment by StevenClontz** [comment]
I agree -- this is more for the sample solutions (I want to require them to write an augmented matrix, but can't because our sample solutions don't do that).

**Comment by siwelwerd** [comment]
I am leaning towards wanting to rewrite many of the V questions in the following format:

Consider the statement "v1 is a linear combination of the vectors v2,v3, and v4"
(a) Write an equivalent statement in terms of solution(s) of a vector equation or a system of linear equations.
(b) Determine if these statements are true or false. Be sure to explain your reasoning.

Maybe need to tweak the language a bit, but I am thinking this is a way to get them to state the definition (as you asked for elsewhere) that leads them towards stating "the" definition, and not some property of a matrix.  I might even want to grade this as two separate standards.

**Comment by StevenClontz** [comment]
Perhaps amend (b) to say

(b) Explain why the statement you provided for (a) is true or false.

to make super explicit that they need to use that language in part (b).

I think your overall idea is probably better than my other suggestion, as it's more explicit about what we mean by "the definition".

**Comment by StevenClontz** [comment]
I know that V10 at least has a generated exercise with a zero-column. We need to reroll any generated matrices with a zero-column. (This is probably more a Mastr feature request: we really need a global helper function that rolls "nice" matrices for use in exercises.)

**Comment by StevenClontz** [comment]
> 
> 
> I know that V10 at least has a generated exercise with a zero-column. We need to reroll any generated matrices with a zero-column. (This is probably more a Mastr feature request: we really need a global helper function that rolls "nice" matrices for use in exercises.)

Wait no. When finding eigenspaces we need to compute kernels with zero columns. So when we tweak E3&V10 to possibly use Euclidean vector equations instead of linear systems, we should do a check for zero columns, and if so, force using a Euclidean vector equation so it's not ambiguous.
