### ISSUE TITLE
Refactor Module V exercises to use random_matrix

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#116]
V02 should be refactored to use a random_matrix simialr to other exercises. This will allow us to provide the student/instructor with a relevant matrix/RREF in the answer, for convenience when practicing/grading (e.g. the student can determine if the issue was with the matrix calculation or the concept itself).

**Comment by siwelwerd** [comment]
Probably also V03, V05, V06, V07, V08, and V09. Changing the title of this accordingly.

**Comment by StevenClontz** [comment]
I also think we might need to lower the dimension of things a bit: I don't think we need them to be typing out 4x6 matrices when 3x5 is probably sufficient to demonstrate mastery of the concept.

**Comment by StevenClontz** [comment]
I'll work on this tomorrow I think, depending on if I get caught back up in my grading. It should be easy enough to do as we have similar exercises for other standards.

**Comment by siwelwerd** [comment]
Students were having me do some RREF calculations that produced unpleasant looking matrices for V03. I won't have time to fix it today, but I can see the logic error; this should be resolved by using the random_matrix approach though.

**Comment by StevenClontz** [comment]
I also think it might make sense to reword V2 to say something like "if yes, provide the witnessing linear combination".

**Comment by siwelwerd** [comment]
I'm not sure I like having that in the prompt (also should be "a" not "the"); that is one valid explanation but there are others. I am happy if they justify the existence of a solution to an appropriate system, even if they don't write down a solution.

**Comment by StevenClontz** [comment]
I think there's value in it, but not strongly enough to tweak the exercise
if you don't agree.


Steven Clontz
https://clontz.org - steven.clontz@gmail.com

**Comment by StevenClontz** [comment]
I believe this is closed by 17e220528d64ee504de738c4e6de1eec529ce03a -- close the issue if I'm correct.
