### ISSUE TITLE
Update standards list

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#117]
The list of standards should probably be updated to reflect the change in expectations; for example, V2 should say "I can explain why" rather than "I can determine".

**Comment by StevenClontz** [comment]
Strong agree. Each E1 should give either a linear system, a vector equation, or an augmented matrix, and students are tasked with describing the corresponding other two. And the activities would need to be updated to reflect this.

**Comment by siwelwerd** [comment]
@StevenClontz , please look at https://github.com/StevenClontz/tbil-la/blob/master/pdf/standards.pdf and verify you are happy with the revised standards; if so, you can close this.
