### ISSUE TITLE
Limit V04 to R3 subspaces

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#118]
I don't think there's any conceptual importance to working with R3/R4 vectors in standard V04; they just add time needed to write things out rigorously (and add time to check solutions carefully). I think I'd like to refactor these exercises to only consider subsets of R2. Let me know if you're okay with that and I'll go ahead and to this.

**Comment by StevenClontz** [comment]
@siwelwerd

**Comment by siwelwerd** [comment]
Conversely, I might argue that this should only be done in R^4 or higher, where students can't use geometry. If questions are all R^2, the questions become "Is it a line through the origin or not".

**Comment by StevenClontz** [comment]
Well, that's a fair point. But the intuition is always that simple: "is the equation a linear combination of the variables equaling zero". The interesting part is if they can verify the subspace property by the definition, once they've done the quick work of ruling out the subset that uses an absolute value or a square.

**Comment by StevenClontz** [comment]
Somewhat related: I've thought about having advanced projects this semester. ("If you can come to my office and show me without notes a whiteboard proof that every subspace of R2 is a line passing through the origin, I'll give you both V04 checkmarks automatically.")

**Comment by siwelwerd** [comment]
I also think there's value in having more variety in what the problems look like. 

Is there really that much more writing? If you increase the dimension by one, you have to write one more component on 3, maybe 4 vectors. The time to actually check depends on what the defining equation(s) look like, not how many components the vector has.

**Comment by StevenClontz** [comment]
More writing leaves more opportunity for "typos" which increases the number of required revisions. And the equations are necessarily shorter for two-variable examples. When I compare a current 2D and 4D exercise, I think the 2D exercise's solution is measurably shorter to write and review.

**Comment by StevenClontz** [comment]
Possible compromise: stick to R3? I'm okay with all our subspaces being planes passing through the origin (as okay as I am having all subspaces being n-spaces passing through R^(n+1)'s origin as we have currently implemented).

**Comment by siwelwerd** [comment]
Yeah, let's just cut it down to R^3.

**Comment by StevenClontz** [comment]
I'll implement this today most likely. Do we want 1D subspaces in addition
to 2D? E.g. 2x=3y=5z. Or maybe punt that until after the semester?

**Comment by siwelwerd** [comment]
I don't think any of the activities or readiness materials have any sets with two constraints (because of your general concern that adding constraints increases time needed to check things), so I anticipate two constraints causing cognitive overload.

**Comment by StevenClontz** [comment]
That matches my thoughts as well. So I'll simply make our examples planes
in R3, and non-examples other surfaces in R3.

At this stage I wonder if V04 shouldn't just be revisited from scratch. If
we're just looking at Euclidean subspaces, they're all just solutions sets
to homogeneous systems. And would it serve our students better to prove a
set is a subspace by providing/proving a set that spans it?

**Comment by siwelwerd** [comment]
Hmm. I'll think about this. Even for non-Euclidean spaces, every subspace is the kernel of some linear transformation.
