### ISSUE TITLE
tracking PDFs

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#120]
I've hit the issue of not being able to add modified PDFs to the repo (which I think[?] came up before). If I recall, this is a result of something you've done to support your modified builds split up by section.

I don't want to break your workflow so I'll let you figure out how to build the updated sample solution in c8020d61 and add its PDF to the repo.

Long-term I'd recommend custom builds should be done separate from the basic repo. But this might be wontfix as the PreTeXt refactor will deprecate this issue anyway I think.

**Comment by siwelwerd** [comment]
Run `git ls-list -v`. If a file is preceded by a lower case 'h', it is marked --assume-unchanged. I believe the command to revert that is `git update-index --no-assume-unchanged FILE`

**Comment by siwelwerd** [comment]
As an aside, I am going to try and find a better way to allow local versions this summer. Maybe by then the repository will be stable enough that forking at the beginning of the semester would be the way to go.

**Comment by StevenClontz** [comment]
For what it's worth, I still think supporting local versions in the main repository is an anti-pattern (although if you want to maintain a personal customization workflow then go wild). If we're looking for wide adoption then the materials ideally should be suitable for multiple environments out-of-the-box.

**Comment by siwelwerd** [comment]
There are no local versions in the repository. All there is are instructions to allow instructor/developers to change files locally, and not have those changes pushed up to the repository.

So if you are still having issues, I believe the problem is on your end, not anything with the repository.

**Comment by StevenClontz** [comment]
I got capital H when running `git ls-files -v`, and you built the changes in 64e4db513bc1c8b1974e284a4e7f77b6b3c53fa5 so I'm closing this for now.
