### ISSUE TITLE
Module M Tweaks

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#122]
- I still don't love the last question on the RAT.
- An introductory observation about composing linear maps, with a brief reminder of how to evaluate a linear map when given the matrix, would help the first part of M run smoother.
- Activities M1 and M2 worked better when I had students work both of them together. 
- There is a small typo in M6

**Comment by siwelwerd** [comment]
- I don't like the prompt on Part 1 of M7. I'd rather it ask what are the domain and codomain of the maps.
- Similarly, the language of Definition M5 and Observation M8 should place more emphasis on the maps than the dimensions of the matrices.

**Comment by StevenClontz** [comment]
I thought we already changed this, but labeling the matrices as A,B,C would be useful. In particular I'm seeing a lot of ABs where BA should be when they label, so I'm not sure the ABs where they aren't specifically labeling are valid.

**Comment by StevenClontz** [comment]
For convenience I want to include the RREF of the matrix in M2's generated answers.

**Comment by siwelwerd** [comment]
> I thought we already changed this, but labeling the matrices as A,B,C would be useful in M1 exercises. In particular I'm seeing a lot of ABs where BA should be when they label, so I'm not sure the ABs where they aren't specifically labeling are valid.

Yeah, why did we change that in the first place?

**Comment by StevenClontz** [comment]
It looks like I wrote M1 and haven't touched it since the first commit: https://github.com/StevenClontz/tbil-la/commits/master/exercises/mastr/M1.sage

I just never added ABC labels. So I'll fix that down the road.
