### ISSUE TITLE
Clarity in explanations

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#123]
I had a thought about how our exercises can be reworded to perhaps more clearly request the insights we're looking for. What if we requested students to write down appropriate definitions first, and then request that they use their definition to explain a property? E.g.

"Give the definition of an invertible matrix. Then use this definition to explain why the following matrix is or is not invertible."

Since we never define properties in terms of matrix features, this should clearly communicate to students that only writing about pivots is insufficient support, rather than just saying that it doesn't "explain" enough.

**Comment by siwelwerd** [comment]
I am not opposed to this but I don't think it will help very much. Instead of saying "You need to explain more" we will say "That's not the definition" when they say "The definition of linear independence is that every column is a pivot column" (my students already say things like this). Broadly speaking, our students don't know what a definition is.

**Comment by StevenClontz** [comment]
Our students don't know what a definition is right now because our assessment structure doesn't require them to. I expect that with this change students will be more mindful of the distinction.

**Comment by StevenClontz** [comment]
Here is a quick run-down of how we might rewrite each prompt to get the level of rigor we're looking for. I'm also throwing in other tweaks we've discussed that don't quite fit this issue. Note a lot of parts (a) and (b); I think that will help alleviate the "but I got the right answer"s.

- E1: Given the following [linear system|Euclidean vector equation|augmented matrix], write equivalent [other two things].
- E2: (keep as-is)
- E3: Show how to find the solution set of the following [linear system|Euclidean vector equation].
- V01: (keep as-is)
- V02: [The vector [vector] belongs to [span]|The vector [vector] is a linear combination of [set of vectors]].
  - (a) Rewrite this statement using a vector equation.
  - (b) Explain why your statement is true or false.
- V03: The set of vectors [set] spans [R^n].
  - (a) Rewrite this statement using a vector equation.
  - (b) Explain why your statement is true or false.
- V04: (keep as-is)
- V05: The set of vectors [set] is linearly independent.
  - (a) Rewrite this statement using a vector equation.
  - (b) Explain why your statement is true or false.
- V06: The set of vectors [set] is a basis for [R^n].
  - (a) Rewrite this statement in terms of other vector properties.
  - (b) Explain why your statement is true or false.
- V07: Consider the subspace W=[set of vectors] of [R^n].
  - (a) Find a basis for W.
  - (b) Explain why your set is a basis.
- V08:
  - (a) Define the dimension of a vector space.
  - (b) Find the dimension of W=[span].
- V09: Consider the subspace W=[set of polynomials/matrices] of [all polynomials/matrices].
  - (a) Describe a Euclidean subspace W' that models the same information.
  - (b) Use W' to find a basis for W.
- V10: Consider the homogeneous [system|vec eq].
  - (a) Find its solution space.
  - (b) Give a basis for this solution space.

Stopping here for tonight in case I'm going off in a direction you're not happy with.

**Comment by siwelwerd** [comment]
I am probably not going to think really hard about these until August, so feel free to leave your fresh thoughts on the rest here. V8 and V9 are my least favorite of your list at the moment.

I thought for E2, we discussed also providing them a matrix not in RREF and explaining why it wasn't in RREF.

**Comment by siwelwerd** [comment]
I think for V9, I would rather do something like

V09: The set of  [polynomials/matrices] [set] is linearly independent.
(a) Rewrite this statement using a [polynomial/matrix] equation.
(a2) Rewrite this statement using a system of equations
(b) Explain why your statement is true or false.

**Comment by StevenClontz** [comment]
I like your V09 revision. Although it probably fits better after V05 in the order since it doesn't rely on a notion of basis anymore.

I'm not sure if I want to randomly pick spanning instead of independence.

**Comment by siwelwerd** [comment]
Right, didn't we used to ask all sorts of things about polynomials? Do you remember why we changed it to only about bases?

I have also mused about an option for spanning P^n or M_n as well. On the one hand, that's a bit of extraneous cognitive demand, but on the other, don't we want them to kind of synthesize everything in this kind of question?

I am still thinking about V8; what do you think about merging it with V7? Honestly, the most trouble I have  on V8 is people saying dim V = R^3 (which earns a W), so I doubt it will cause much trouble as extra part of V7.

**Comment by StevenClontz** [comment]
There was too much variance in the "old" V09 - to make all questions relatively the same difficulty we switched everything to basis. But I think independence/spanning is comparable.

I like merging the questions about the basis of a subspace and dimension.

**Comment by StevenClontz** [comment]
Also if we merge V07/V08 and add an M4, we keep the same total # of standards, whatever that's worth.

**Comment by siwelwerd** [comment]
I started with the sample exercises so I can get @StevenClontz 's feedback before propagating the changes throughout.  The following standards changed: E1,E2,V2,V3,V5,V6,V7,V8,V9,A2,A3,M4(new),G1.  

https://github.com/StevenClontz/tbil-la/blob/master/pdf/sample-exercises.pdf

E3 did not change in the sample, but the exercises will need to change to add in the vector equation option.

**Comment by StevenClontz** [comment]
In A3 you reference the "rank-nullity theorem". Last semester we didn't use the words "rank" or "null space". Perhaps "image-kernel dimension theorem" is more meaningful? Or should we be using the words "rank" and "null" in class?

**Comment by StevenClontz** [comment]
In G1, instead of "What is det(B)?", do we want "Use matrix multiplication to explain how to compute det(B)."? That way the student needs to say something like. "Let R=[stuff]. Then det(B)=det(RA)=det(R)det(A)=[answer]"'.

**Comment by siwelwerd** [comment]
For A3, it was based on this: https://github.com/StevenClontz/tbil-la/issues/121#issuecomment-623145303 . I have never seen that theorem referred to as anything other than "Rank-Nullity Theorem". Definitely need to add activities to go along with it.

**Comment by siwelwerd** [comment]
In G1, I am okay if they don't use matrix multiplication -- that aspect was shifted into M4.
