### ISSUE TITLE
Module G Tweaks

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#124]
- Should we use 4x4 matrices when doing row operations and determinants? I observed students using magic diagonals to compute determinants of these simple 3x3 matrices instead of reasoning.
- The RAT should probably cover the row operations as matrix multiplication.
- Activity G34: We spent more like 20 minutes on this than the labeled 10.
- As a result, we skipped activity G37, which I don't really like. Maybe it can be omitted.

**Comment by StevenClontz** [comment]
Yes!! to 4x4 matrices.

**Comment by siwelwerd** [comment]
Some of the G1 problems provide commuting P and Q (for example, on the test P was a diagonal matrix affecting row 1, while Q was a permutation matrix of the second and third rows). For part (c), I think producing the matrix PQ is a valid solution, but if they don't label it now I can't tell if they did PQ or QP.

**Comment by StevenClontz** [comment]
I'm not following. I believe parts (a) and (b) specify what P and Q are, so I'm not sure how they'd reasonably respond except with PQA or QPA.

**Comment by siwelwerd** [comment]
They computed PQ (or QP), and wrote that multiplied by A for part (c). Basically, they wrote 
(a) P=[[5,0,0],[0,1,0],[0,0,1]]
(b) Q=[[1,0,0],[0,0,1],[0,1,0]]
(c) [[5,0,0],[0,0,1],[0,1,0]]A

**Comment by StevenClontz** [comment]
Oh I see. So we should make sure P and Q don't commute.

**Comment by siwelwerd** [comment]
Right.
