### ISSUE TITLE
Add multiplication of matrices using technology

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#91]
Add a part 3 to activity M7 which says `Use technology to check your work.`

**Comment by StevenClontz** [comment]
Welp, right after I reported this, I realized that we already added a separate activity on the next "day" (for me, 5 minutes later) that talks about using technology, which I was able to skip (since I had them do the tech stuff on M7 ad hoc).

So this should be closed; although it emphasizes that our activities are still very opinionated about the length of a class period. (Tagging @siwelwerd in case you have further discussion to document.)

**Comment by siwelwerd** [comment]
That is one of the main reasons I added the sectioning feature. This allows an instructor to reorder activities, introduce additional activities, add conclusion slides at the end of the day, etc.  So maybe if I get that fixed and/or documented better that will help with this issue.

**Comment by StevenClontz** [comment]
Yep I remember you saying you developed something for this purpose, but I don't know how to use it (and for the purposes of this semester, using the materials lumped together isn't a huge inconvenience, particularly if I'd just peek ahead through the slides while they take their quiz each morning so I know what's coming up).
