### ISSUE TITLE
Consider moving row operation matrix discussion to G.

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/tbil-la#92]
We used to have the discussion of row operation matrices in M because (a) it's about matrix multipication and (b) we had a standard for it in M. However, (b) is no longer true. I'll revisit this issue again once I cover the discussion in G, but I suspect that we'd recover a bit of time by moving this discussion fully into G.

**Comment by siwelwerd** [comment]
Let's chat about this next week.

**Comment by siwelwerd** [comment]
After teaching this summer, I am inclined to leave this like it is.

**Comment by siwelwerd** [comment]
Having just done this section again today, I like these activities where they are.

**Comment by StevenClontz** [comment]
I'll close this then, but make a note to reopen in the spring when I teach it again if I think think it should be moved.

**Comment by StevenClontz** [comment]
No way am I using this semester to decide to dig up this topic, despite a reminder popping up in my email to consider it. Leaving closed indefinitely. (-:

**Comment by StevenClontz** [comment]
Actually I'm a liar and I will reopen this.

Right now I'm getting annoyed at the fact that I have students who seem to get everything about G1 except the order of the matrices (i.e. part c). Since that's a toss-up I cannot let them revise, even though they may have computed the determinant correctly by using det(PQA)=det(P)det(Q)det(A). So perhaps we keep the row operation discussion in M, but then I'd prefer assessing understanding of how the elementary matrices work in M, separate from how they are used to compute determinants in G.

**Comment by siwelwerd** [comment]
So you are advocating for an additional M standard? Or for removing part (d) from existing G1 and moving it to M?

I haven't graded any G1 yet (It's on their quiz they are taking today), but having finished our discussion of determinants again today, I like how the class activities have gone through this part. So let's tweak the assessment maybe.

**Comment by StevenClontz** [comment]
Yeah, basically parts (a-c) as M4, and the new G1 asks for the determinant of PA and QA separately.

**Comment by siwelwerd** [comment]
Agreed on new M4. Not sure exactly what you mean on G1; what about

(a) Suppose A is a 3 x 3 matrix with determinant 2. What is the determinant of the matrix
obtained by applying R1 + 4R2 -> R1   to A .
(b) Suppose B is a 3 x 3 matrix with determinant 5. What is the determinant of the matrix
obtained by applying  R1 <--> R2 to B. ?
(c) Suppose C is a 3 x 3 matrix with determinant 7. What is the determinant of the matrix
obtained by applying 6R3 -> R3   to C ?

**Comment by StevenClontz** [comment]
I like asking for all 3 types. I don't see a reason to differentiate A/B/C, and the students need better prompts to appeal to matrix multiplication. How about (incorporating your 4x4 note from another thread):

Let A be a 4x4 matrix with determinant [random].
(a) Use matrix multiplication to describe the matrix B obtained by applying [row operation] to A. Then find det(B).
(b-c) [same, but other 2 types of row ops]

**Comment by siwelwerd** [comment]
Standards have been changed, aligning the activities is part of #127, so I am closing this one.
