### ISSUE TITLE
Revise problems

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/tbil-la#99]
I think a number of assessment problem prompts can (should) be revised to elicit more detailed student reasoning. For example:

- On E2, I think a two part question of "Show RREF(A)=(whatever the RREF is) " followed by "Explain why (some matrix close to but not in RREF) is not in RREF". Many students like to use their calculator to find the RREF, and work towards that, but have trouble when I ask them how they know something is in RREF or not.
- V2 might be phrased better as "Explain why v_1 is (or is not) a linear combination of v_2,v_3,v_4".
- V3 Similarly, "Explain why ... "
- V5 Similarly, "Explain why ... "
- V6 Similarly, "Explain why ... "

**Comment by siwelwerd** [comment]
I am presently annoyed grading A4 problems. Students often  will only answer "T is injective" and not mention surjectivity; or, if  it is bijective or neither, they say something like "T is both injective  and surjective because there are pivots in all rows and columns", so it  is unclear if they know which one means injective and which one means  surjective. Thus I am recommending revising A4 problems along the  following lines: 
"Here is a map T: R^m --> R^n given by ... 
(a) Explain why T is or is not injective. 
(b) Explain why T is or is not surjective."

**Comment by siwelwerd** [comment]
I believe this is complete, but am leaving this open until @StevenClontz has a chance to give the sample exercise file a quick once-over for any glaring discrepancies with the new Mastr prompts.

**Comment by StevenClontz** [comment]
V1 needs work - inconsistency on (x_n,y_n) vs (x_1,x_2), and I wouldn't accept your solution for (b) without revision.

There's a typo ("set") in V3.

V4 has the same issue with V1: I strongly prefer picking a specific counterexample rather than proving the equality fails in general. I'll compromise by offering two version of this (and V1)'s solution.

Rather than outline further, I'll just make a new commit (tomorrow) with some proposed changes that I think will make both of us happy and I'll comment again once that's ready.

**Comment by StevenClontz** [comment]
Please review the changes made in a5d771d6.

I'd honestly rather remove "Solution method 1" in V1,V4,A1, but if you still strongly prefer that method then it's best to keep both in there (assuming we'd both accept either method).

**Comment by siwelwerd** [comment]
I can live with what you have now. I took out your preferred approach when I revised the solutions because I noticed students using that method were having more trouble than students who were using the first method.
